#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

# dnf install mingw64-gcc

git_version

function build () {
	local TOOL=$1
	pushd "$ROOT/$TOOL" > /dev/null
	go build \
		"${@:2}" \
		-ldflags " \
			-X '$MODULE/version.GitVersion=$VERSION' \
			-X '$MODULE/version.GitRevision=$REVISION' \
			-X '$MODULE/version.Timestamp=$TIMESTAMP'"
	popd > /dev/null
}

m 'posix'
build library -buildmode=c-shared -o="$ROOT/dist/libkutil.so"

m 'windows'
GOOS=windows CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc \
build library -buildmode=c-shared -o="$ROOT/dist/kutil.dll"

m 'wasm'
GOOS=js GOARCH=wasm build library -o="$ROOT/dist/kutil.wasm"
