#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

gofmt -w -s -e \
	"$ROOT/cobra" \
	"$ROOT/exec" \
	"$ROOT/fswatch" \
	"$ROOT/kubernetes" \
	"$ROOT/library" \
	"$ROOT/problems" \
	"$ROOT/protobuf" \
	"$ROOT/reflection" \
	"$ROOT/streampackage" \
	"$ROOT/terminal" \
	"$ROOT/transcribe" \
	"$ROOT/util" \
	"$ROOT/version"
